# Generated by Django 5.1.3 on 2024-12-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_payment_city_remove_payment_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default='patherdi nashik'),
            preserve_default=False,
        ),
    ]
