# Generated by Django 5.1.3 on 2024-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_order_options_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
